"""Temporary-to-formal inventory transfer states and labels."""

TRANSFER_STATUS_AWAITING_PURCHASE = "awaiting_purchase"
TRANSFER_STATUS_ACCEPTANCE_IN_PROGRESS = "acceptance_in_progress"
TRANSFER_STATUS_ACCEPTANCE_FAILED = "acceptance_failed"
TRANSFER_STATUS_FORMAL_INBOUND_PARTIAL = "formal_inbound_partial"
TRANSFER_STATUS_FORMAL_INBOUND_COMPLETE = "formal_inbound_complete"
TRANSFER_STATUS_RESERVING = "reserving"
TRANSFER_STATUS_AUTO_CLAIM_CREATING = "auto_claim_creating"
TRANSFER_STATUS_AUTO_CLAIM_PENDING = "auto_claim_pending"
TRANSFER_STATUS_AUTO_CLAIM_EXCEPTION = "auto_claim_exception"
TRANSFER_STATUS_PAUSED = "paused"
TRANSFER_STATUS_EXCEPTION = "exception"
TRANSFER_STATUS_CANCELLED = "cancelled"
TRANSFER_STATUS_COMPLETED = "completed"

TRANSFER_ACTIVE_STATUSES = frozenset(
    {
        TRANSFER_STATUS_AWAITING_PURCHASE,
        TRANSFER_STATUS_ACCEPTANCE_IN_PROGRESS,
        TRANSFER_STATUS_ACCEPTANCE_FAILED,
        TRANSFER_STATUS_FORMAL_INBOUND_PARTIAL,
        TRANSFER_STATUS_FORMAL_INBOUND_COMPLETE,
        TRANSFER_STATUS_RESERVING,
        TRANSFER_STATUS_AUTO_CLAIM_CREATING,
        TRANSFER_STATUS_AUTO_CLAIM_PENDING,
        TRANSFER_STATUS_AUTO_CLAIM_EXCEPTION,
        TRANSFER_STATUS_PAUSED,
        TRANSFER_STATUS_EXCEPTION,
    }
)
TRANSFER_TERMINAL_STATUSES = frozenset(
    {TRANSFER_STATUS_CANCELLED, TRANSFER_STATUS_COMPLETED}
)

TRANSFER_STATUS_LABELS = {
    TRANSFER_STATUS_AWAITING_PURCHASE: "等待采购处理",
    TRANSFER_STATUS_ACCEPTANCE_IN_PROGRESS: "验收处理中",
    TRANSFER_STATUS_ACCEPTANCE_FAILED: "验收失败",
    TRANSFER_STATUS_FORMAL_INBOUND_PARTIAL: "正式入库不足",
    TRANSFER_STATUS_FORMAL_INBOUND_COMPLETE: "正式入库完成，等待结算",
    TRANSFER_STATUS_RESERVING: "正在预留正式库存",
    TRANSFER_STATUS_AUTO_CLAIM_CREATING: "正在创建自动领用",
    TRANSFER_STATUS_AUTO_CLAIM_PENDING: "等待自动领用完成",
    TRANSFER_STATUS_AUTO_CLAIM_EXCEPTION: "自动领用异常",
    TRANSFER_STATUS_PAUSED: "已暂停",
    TRANSFER_STATUS_EXCEPTION: "异常",
    TRANSFER_STATUS_CANCELLED: "已取消",
    TRANSFER_STATUS_COMPLETED: "已完成",
}

TRANSFER_ORIGIN_TYPE = "temporary_transfer"
